#!/usr/bin/env python3
"""
AI DevStudio Installer — cross-platform, multi-tool.

Targets:
  claude  (default)  Install to ~/.claude/skills/ for Claude Code CLI
  gemini             Generate GEMINI.md for Gemini CLI
  codex              Generate AGENTS.md for Codex CLI / OpenCode
  cursor             Generate .cursor/rules/ for Cursor
  aider              Generate aider-skills/ + .aider.conf.yml for Aider
  generic            Generate system-prompt.md for any AI tool or model API

Usage:
  python install.py                     # Claude Code (default)
  python install.py --target gemini
  python install.py --target generic --output my-prompt.md
"""

import argparse
import shutil
import sys
from pathlib import Path


def strip_frontmatter(text: str) -> str:
    """Remove YAML frontmatter enclosed in --- delimiters."""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return text
    end = next(
        (i for i, ln in enumerate(lines[1:], 1) if ln.strip() == "---"), None
    )
    if end is None:
        return text
    return "".join(lines[end + 1 :])


def iter_skills(skills_dir: Path):
    """Yield (name, stripped_content) for each skill in sorted order."""
    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            continue
        yield skill_dir.name, strip_frontmatter(skill_file.read_text(encoding="utf-8"))


TOOL_MAPPING = """
| Skill tool | Generic equivalent           |
|------------|------------------------------|
| Read       | Read file contents           |
| Write      | Write/create file            |
| Edit       | Edit/patch file              |
| Bash       | Run shell command            |
| Grep       | Search file contents (regex) |
| Glob       | List files by pattern        |
| TodoWrite  | Track tasks in memory        |
"""


# ── Target handlers ────────────────────────────────────────────────────────────

def install_claude(skills_dir: Path) -> None:
    dest = Path.home() / ".claude" / "skills"
    dest.mkdir(parents=True, exist_ok=True)
    skill_dirs = [d for d in skills_dir.iterdir() if d.is_dir()]

    existing = [d for d in skill_dirs if (dest / d.name).exists()]
    if existing:
        print(f"[WARNING] Found {len(existing)} existing skills in {dest}")
        resp = input("Overwrite existing skills? (y/N): ")
        if resp.lower() != "y":
            print("[CANCELLED]")
            sys.exit(0)

    count = 0
    for skill_dir in sorted(skill_dirs):
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            print(f"  skipping {skill_dir.name} (no SKILL.md)")
            continue
        target_dir = dest / skill_dir.name
        if target_dir.exists():
            shutil.rmtree(target_dir)
        shutil.copytree(skill_dir, target_dir)
        print(f"  + {skill_dir.name}")
        count += 1

    manifest = dest / ".ai-devstudio-manifest"
    manifest.write_text("\n".join(d.name for d in sorted(skill_dirs)) + "\n")
    print(f"\n[SUCCESS] Installed {count} skills to {dest}")
    print("Type / in Claude Code to see available skills")


def install_generic(skills_dir: Path, output: Path) -> None:
    parts = [
        "# AI DevStudio Skills — System Prompt\n\n"
        "You are an expert software engineering assistant. The following skills define\n"
        "specialized workflows. Follow a skill's instructions when the user invokes it by name.\n\n"
        + TOOL_MAPPING + "\n---\n\n"
    ]
    count = 0
    for name, content in iter_skills(skills_dir):
        parts.append(f"## Skill: {name}\n\n{content}\n\n---\n\n")
        count += 1
    parts.append(f"<!-- Generated by AI DevStudio. {count} skills. -->\n")
    output.write_text("".join(parts), encoding="utf-8")
    print(f"[OK] Generated {output} with {count} skills")
    print("     Pass this file as a system prompt to any AI tool or model API.")


def install_gemini(skills_dir: Path, output: Path) -> None:
    parts = [
        "# AI DevStudio Skills for Gemini CLI\n\n"
        "This file is read automatically by Gemini CLI as project context.\n"
        "Invoke a skill by name: \"Use the commit skill\", \"Run security-scan\", etc.\n\n"
        + TOOL_MAPPING + "\n---\n\n## Skills Reference\n\n"
    ]
    count = 0
    for name, content in iter_skills(skills_dir):
        parts.append(f"### {name}\n\n{content}\n\n---\n\n")
        count += 1
    parts.append(f"<!-- Generated by AI DevStudio Gemini adapter. {count} skills. -->\n")
    output.write_text("".join(parts), encoding="utf-8")
    print(f"[OK] Generated {output} with {count} skills")
    print("     Place GEMINI.md in your project root. Gemini CLI will load it automatically.")


def install_codex(skills_dir: Path, output: Path) -> None:
    parts = [
        "# AI DevStudio Skills for Codex CLI / OpenCode\n\n"
        "This file is read as agent context. Invoke a skill by name in your prompt.\n\n"
        + TOOL_MAPPING + "\n---\n\n## Skills\n\n"
    ]
    count = 0
    for name, content in iter_skills(skills_dir):
        parts.append(f"### {name}\n\n{content}\n\n---\n\n")
        count += 1
    parts.append(f"<!-- Generated by AI DevStudio Codex adapter. {count} skills. -->\n")
    output.write_text("".join(parts), encoding="utf-8")
    print(f"[OK] Generated {output} with {count} skills")
    print("     Place AGENTS.md in your project root. Codex CLI will load it automatically.")


def install_cursor(skills_dir: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    count = 0
    for name, content in iter_skills(skills_dir):
        rule_file = output_dir / f"skill-{name}.md"
        rule_file.write_text(
            f"---\ndescription: AI DevStudio skill: {name}\nalwaysApply: false\n---\n\n{content}",
            encoding="utf-8",
        )
        count += 1
    print(f"[OK] Generated {count} rule files in {output_dir}/")
    print("     Cursor loads these automatically. Reference with @skill-<name>.")


def install_aider(skills_dir: Path, output_dir: Path, write_config: bool = True) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    read_list = []
    count = 0
    for name, content in iter_skills(skills_dir):
        out = output_dir / f"{name}.md"
        out.write_text(f"# Skill: {name}\n\n{content}", encoding="utf-8")
        read_list.append(str(out))
        count += 1

    if write_config:
        config = Path(".aider.conf.yml")
        lines = ["# Auto-generated by AI DevStudio aider adapter", f"# Loads all {count} skills as read-only context.", "read:"]
        lines += [f"  - {p}" for p in read_list]
        config.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"[OK] Generated .aider.conf.yml — skills load automatically when you run aider")

    print(f"[OK] Generated {count} skill files in {output_dir}/")
    print("     Run: aider  (config auto-loads skills)")


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="AI DevStudio installer")
    parser.add_argument("--target", default="claude",
                        choices=["claude", "gemini", "codex", "cursor", "aider", "generic"],
                        help="Target tool (default: claude)")
    parser.add_argument("--output", default=None,
                        help="Output file (generic/gemini/codex) or output dir (cursor/aider)")
    args = parser.parse_args()

    script_dir = Path(__file__).parent.absolute()
    skills_dir = script_dir / "skills"

    if not skills_dir.exists():
        print(f"[ERROR] Skills directory not found: {skills_dir}")
        sys.exit(1)

    if args.target == "claude":
        install_claude(skills_dir)

    elif args.target == "generic":
        out = Path(args.output or "system-prompt.md")
        install_generic(skills_dir, out)

    elif args.target == "gemini":
        out = Path(args.output or "GEMINI.md")
        install_gemini(skills_dir, out)

    elif args.target == "codex":
        out = Path(args.output or "AGENTS.md")
        install_codex(skills_dir, out)

    elif args.target == "cursor":
        out_dir = Path(args.output or ".cursor/rules")
        install_cursor(skills_dir, out_dir)

    elif args.target == "aider":
        out_dir = Path(args.output or "aider-skills")
        install_aider(skills_dir, out_dir)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[CANCELLED]")
        sys.exit(0)
    except Exception as e:
        print(f"\n[ERROR] {e}")
        sys.exit(1)
