#!/bin/bash
# Aider adapter — generates two artifacts:
#   1. aider-skills/          — stripped SKILL.md files ready for --read
#   2. .aider.conf.yml        — read-files list so aider loads them automatically
#
# Usage:
#   ./adapters/aider.sh [--output-dir <dir>] [--skills-dir <dir>] [--no-config]
#
# With .aider.conf.yml in place, just run: aider
# Without it, pass skills individually: aider --read aider-skills/commit.md

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=adapters/utils.sh
source "$SCRIPT_DIR/utils.sh"

SKILLS_DIR="${SKILLS_DIR:-$SCRIPT_DIR/../skills}"
OUTPUT_DIR="${OUTPUT_DIR:-aider-skills}"
WRITE_CONFIG=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
        --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
        --no-config) WRITE_CONFIG=false; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

mkdir -p "$OUTPUT_DIR"
echo "Generating aider skill files -> $OUTPUT_DIR/"

skill_count=0
READ_LIST=""
while IFS= read -r -d '' skill_dir; do
    skill_name="$(basename "$skill_dir")"
    skill_file="$skill_dir/SKILL.md"
    [[ -f "$skill_file" ]] || continue

    out="$OUTPUT_DIR/${skill_name}.md"
    {
        printf '# Skill: %s\n\n' "$skill_name"
        strip_frontmatter "$skill_file"
    } > "$out"

    READ_LIST="${READ_LIST}  - ${OUTPUT_DIR}/${skill_name}.md\n"
    ((skill_count++)) || true
done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

if [[ "$WRITE_CONFIG" == true ]]; then
    {
        printf '# Auto-generated by Claude DevStudio aider adapter\n'
        printf '# Loads all %d skills as read-only context.\n' "$skill_count"
        printf 'read:\n'
        printf '%b' "$READ_LIST"
    } > .aider.conf.yml
    echo "[OK] Generated .aider.conf.yml — skills load automatically when you run aider"
fi

echo "[OK] Generated $skill_count skill files in $OUTPUT_DIR/"
echo "     Run: aider  (config auto-loads skills)"
echo "     Or:  aider --read $OUTPUT_DIR/commit.md --read $OUTPUT_DIR/review.md ..."
