#!/bin/bash
# Codex adapter — generates AGENTS.md for use with OpenAI Codex CLI.
# Codex CLI reads AGENTS.md from the project root as its agent context.
#
# Usage:
#   ./adapters/codex.sh [--output <file>] [--skills-dir <dir>]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=adapters/utils.sh
source "$SCRIPT_DIR/utils.sh"

SKILLS_DIR="${SKILLS_DIR:-$SCRIPT_DIR/../skills}"
OUTPUT_FILE="${OUTPUT_FILE:-AGENTS.md}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "Generating Codex CLI context file -> $OUTPUT_FILE"

cat > "$OUTPUT_FILE" <<'HEADER'
# AI DevStudio Skills for Codex CLI

This file is read automatically by Codex CLI as agent context. It provides
99 professional skills — specialized workflows for common development tasks.

## How to Use Skills

Reference a skill by name in your prompt:
- "Use the commit skill"
- "Run security-scan"
- "Apply tdd-red-green to add this feature"

## Tool Name Mapping

Skills reference tool names from Claude Code. Map them to shell equivalents:

| Skill tool | Shell / Codex equivalent |
|------------|--------------------------|
| Read       | cat / head               |
| Write      | tee / redirect           |
| Edit       | sed / patch              |
| Bash       | shell command            |
| Grep       | grep / rg                |
| Glob       | find / ls                |

---

## Skills

HEADER

skill_count=0
while IFS= read -r -d '' skill_dir; do
    skill_name="$(basename "$skill_dir")"
    skill_file="$skill_dir/SKILL.md"
    [[ -f "$skill_file" ]] || continue

    printf '### %s\n\n' "$skill_name" >> "$OUTPUT_FILE"
    strip_frontmatter "$skill_file" >> "$OUTPUT_FILE"
    printf '\n\n---\n\n' >> "$OUTPUT_FILE"
    ((skill_count++)) || true
done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

echo "" >> "$OUTPUT_FILE"
echo "<!-- Generated by AI DevStudio Codex adapter. $skill_count skills. -->" >> "$OUTPUT_FILE"

echo "[OK] Generated $OUTPUT_FILE with $skill_count skills"
echo "     Place AGENTS.md in your project root. Codex CLI will load it automatically."
