#!/bin/bash
# Gemini adapter — generates or updates GEMINI.md for use with Gemini CLI.
# Gemini CLI reads GEMINI.md from the project root as its context file,
# mirroring the CLAUDE.md pattern.
#
# Usage:
#   ./adapters/gemini.sh [--output <file>] [--skills-dir <dir>]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=adapters/utils.sh
source "$SCRIPT_DIR/utils.sh"

SKILLS_DIR="${SKILLS_DIR:-$SCRIPT_DIR/../skills}"
OUTPUT_FILE="${OUTPUT_FILE:-GEMINI.md}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "Generating Gemini context file -> $OUTPUT_FILE"

cat > "$OUTPUT_FILE" <<'HEADER'
# Claude DevStudio Skills for Gemini CLI

This file is read automatically by Gemini CLI as project context. It provides
99 professional skills — specialized workflows for common development tasks.

## How to Use Skills

Invoke a skill by name in your prompt:
- "Use the commit skill to create a conventional commit"
- "Run the security-scan skill on this project"
- "Apply the tdd-red-green skill to implement this feature"

Gemini will follow the skill's step-by-step instructions using its available tools.

## Tool Name Mapping

Skills reference tool names from Claude Code. Map them to Gemini's capabilities:

| Skill tool | Gemini equivalent         |
|------------|---------------------------|
| Read       | read_file                 |
| Write      | write_file / create_file  |
| Edit       | replace_in_file           |
| Bash       | run_shell_command         |
| Grep       | search_files              |
| Glob       | list_files                |

---

## Skills Reference

HEADER

skill_count=0
while IFS= read -r -d '' skill_dir; do
    skill_name="$(basename "$skill_dir")"
    skill_file="$skill_dir/SKILL.md"
    [[ -f "$skill_file" ]] || continue

    printf '### %s\n\n' "$skill_name" >> "$OUTPUT_FILE"
    strip_frontmatter "$skill_file" >> "$OUTPUT_FILE"
    printf '\n\n---\n\n' >> "$OUTPUT_FILE"
    ((skill_count++)) || true
done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

echo "" >> "$OUTPUT_FILE"
echo "<!-- Generated by Claude DevStudio Gemini adapter. $skill_count skills. -->" >> "$OUTPUT_FILE"

echo "[OK] Generated $OUTPUT_FILE with $skill_count skills"
echo "     Place GEMINI.md in your project root. Gemini CLI will load it automatically."
