#!/bin/bash
# Generic adapter — produces a single system-prompt.md usable with any AI tool or model.
# Works with: OpenCode, Kimi K2, Gemini API, OpenAI API, Ollama, LM Studio, or any
# tool that accepts a system prompt or context file.
#
# Usage:
#   ./adapters/generic.sh [--output <file>] [--skills-dir <dir>]
#
# Output: system-prompt.md (default) or --output path

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=adapters/utils.sh
source "$SCRIPT_DIR/utils.sh"

SKILLS_DIR="${SKILLS_DIR:-$SCRIPT_DIR/../skills}"
OUTPUT_FILE="${OUTPUT_FILE:-system-prompt.md}"

# Parse flags
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "Generating generic system prompt -> $OUTPUT_FILE"

cat > "$OUTPUT_FILE" <<'HEADER'
# AI DevStudio Skills — System Prompt

You are an expert software engineering assistant. The following skills define
specialized workflows you can perform when invoked by the user. Each skill
starts with its name (e.g. "commit", "review") and contains step-by-step
instructions.

When the user asks you to perform a task matching a skill name, follow that
skill's instructions precisely. Use only the tools available in your current
environment — map the tool names below to your actual capabilities:

| Skill tool name | Generic equivalent           |
|-----------------|------------------------------|
| Read            | Read file contents           |
| Write           | Write/create file            |
| Edit            | Edit/patch file              |
| Bash            | Run shell command            |
| Grep            | Search file contents (regex) |
| Glob            | List files by pattern        |
| TodoWrite       | Track tasks in memory        |

---

HEADER

skill_count=0
while IFS= read -r -d '' skill_dir; do
    skill_name="$(basename "$skill_dir")"
    skill_file="$skill_dir/SKILL.md"
    [[ -f "$skill_file" ]] || continue

    printf '## Skill: %s\n\n' "$skill_name" >> "$OUTPUT_FILE"
    strip_frontmatter "$skill_file" >> "$OUTPUT_FILE"
    printf '\n\n---\n\n' >> "$OUTPUT_FILE"
    ((skill_count++)) || true
done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

echo "" >> "$OUTPUT_FILE"
echo "<!-- Generated by AI DevStudio generic adapter. $skill_count skills. -->" >> "$OUTPUT_FILE"

echo "[OK] Generated $OUTPUT_FILE with $skill_count skills"
echo "     Pass this file as a system prompt to any AI tool or API."
